#!/bin/bash -ex
    sudo apt-get update -y
    sudo apt-get install apache2 -y
    echo '<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Microsoft Azure App Service - Welcome</title>
  </head>
  <body>
    <h1 style="font-size:30px">
      Hello from <span style="color:blue;">Server1</span>!
	</h1>
  </body>
</html>' | tee /var/www/html/index.html"

